### ISSUE TITLE
无法设置放大倍数上限

### ISSUE THREAD

**Issue by shoulderdh** [Dovar66/FullPhotoView#1]
photoview.setmaximumscale(1.3f) ;  没有效果
![image](https://user-images.githubusercontent.com/14287365/37892219-a2ebf23c-3109-11e8-81c0-1c529a5a83c3.png)

**Comment by Dovar66** [comment]
改成下图这样即可
![_15354282108763](https://user-images.githubusercontent.com/18225009/44699807-8660df00-aab8-11e8-95fa-c3826c962ce6.png)

**Comment by Dovar66** [comment]
改成下图这样即可
![_153542826522](https://user-images.githubusercontent.com/18225009/44699831-a5f80780-aab8-11e8-8a58-6a9e25a05e5a.png)
